/*
 * Timer_config.h
 *
 * Created: 3/26/2023 2:16:15 PM
 *  Author: mohamed abdelslam
 */ 


#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/* options for timer0 mode: 
  OVER_FLOW_MODE
  PHASE_CORRECT_PWM_MODE
  CTC_MODE
  FAST_PWM_MODE
 */
#define TIMER0_MODE    OVER_FLOW_MODE  

/* options for timer0 clock
NO_CLOCK_SOURCE
CPU_CLOCK
CPU_DIV_BY_8
CPU_DIV_BY_64
CPU_DIV_BY_256
CPU_DIV_BY_1024
EXTERNAL_FALLING_EDGE
EXTERNAL_RISING_EDEG
 */
#define TIMER0_CLOCK     CPU_DIV_BY_1024     

/* select option
OC0_DISCONNECTED
TOGG_OC0_ON_COMP_MATCH
CLR_OC0_ON_COMP_MATCH
SET_OC0_ON_COMP_MATCH
 */
#define COMPARE_OUT_MODE    CLR_OC0_ON_COMP_MATCH  
/*select option :
OC0_ENABLED
OC0_DISABLED
 */
#define OC0_STATUS       OC0_DISABLED

/* options for timer2 clock source types
CPU_CLOCK
EXTERNAL_CRYSTAL_ON_TOSC1
 */
#define TIMER2_CLOCK_SOURCE_TYPE       EXTERNAL_CRYSTAL_ON_TOSC1

/* options for timer2 clock source: 
NO_CLOCK_SOURCE
TIMER2_SOURCE_CLOCK
TIMER2_SOURCE_CLOCK_DIV_BY_8
TIMER2_SOURCE_CLOCK_DIV_BY_32
TIMER2_SOURCE_CLOCK_DIV_BY_64
TIMER2_SOURCE_CLOCK_DIV_BY_128
TIMER2_SOURCE_CLOCK_DIV_BY_256
TIMER2_SOURCE_CLOCK_DIV_BY_1024
*/
#define TIMER2_CLOCK     TIMER2_SOURCE_CLOCK_DIV_BY_128  

/* options for timer2 mode: 
  OVER_FLOW_MODE
  PHASE_CORRECT_PWM_MODE
  CTC_MODE
  FAST_PWM_MODE
 */
#define TIMER2_MODE    OVER_FLOW_MODE 

/* select option
OC2_DISCONNECTED
TOGG_OC2_ON_COMP_MATCH
CLR_OC2_ON_COMP_MATCH
SET_OC2_ON_COMP_MATCH
 */
#define TIMER2_COMPARE_OUT_MODE    CLR_OC0_ON_COMP_MATCH 

#define OC2_STATUS       OC2_DISABLED

#endif /* TIMER_CONFIG_H_ */